#!/usr/bin/node

var http = require('http'),
	fs = require('fs'),
	path = require("path"),
	url = require('url');

var mimeTypes = {
	'plain': 'text/plain',
	'css': 'text/css',
	'gif': 'image/gif',
	'htm': 'text/html',
	'html': 'text/html',
	'ico': 'image/x-icon',
	'jpeg': 'image/jpeg',
	'jpg': 'image/jpeg',
	'js': 'text/javascript',
	'mov': 'video/quicktime',
	'mp3': 'audio/mpeg3',
	'mp4': 'video/mpeg',
	'png': 'image/png',
	'swf': 'application/x-shockwave-flash',
	'xml': 'text/xml',
	'zip': 'application/zip',

	get: function(filename){
		return this[path.extname(filename).substr(1)] || this.plain;
	}
};

var statusCodes = {
	200: "OK",
	403: "Forbidden",
	404: "Not Found",
	500: "Internal Server Error"
};

function error(res, code, message)
{
	res.writeHead(code,{'Content-Type': mimeTypes.plain});
	res.write(code + " " + (message || statusCodes[code] || "") + "\n");
	res.end(null);
}

function serveFile(res, filename, stats)
{
	var readStream = fs.createReadStream(filename);

	readStream.on('open', function(){
		res.writeHead(200,{
			'Content-Type': mimeTypes.get(filename),
			'Content-Length': stats.size
		});

		readStream.pipe(res);
	});

	readStream.on('error', function(err){
		error(res, err.code == "EACCES" ? 403 : 500);
	});
}

function serveDirectory(res, path, uri)
{
	res.writeHead(200,{'Content-Type': mimeTypes.html});
	res.write("<h1>Index of " + uri + "</h1>\n");

	statDir(path, function(err, filestats){
		if ( err || !filestats )
		{
			error(res, 500);
		}
		else
		{
			res.write("<ul>\n");

			// Support going up a directory
			if (uri != "/")
			{
				res.write("<li><a href=\"" + (uri.lastIndexOf("/") == 0 ? "/" : uri.substring(0, uri.lastIndexOf("/"))) + "\">..</a></li>\n");
			}

			// List all files
			for ( var file in filestats )
			{
				if ( filestats.hasOwnProperty(file) )
				{
					res.write("<li><a href=\"" + uri + (uri.charAt(uri.length-1) == "/" ? "" : "/") + file + "\">" + file + (filestats[file].isDirectory() ? "/" : "") + "</a></li>\n");
				}
			}

			res.write("</ul>\n");
			res.end(null);
		}
	});
}

function statFile(dir, filename, files, filestats, callback)
{
	var filepath = path.join(dir, filename);
	fs.stat(filepath, function(err, stats){
		filestats[filename] = err ? null : stats;

		// Check all files have been done
		for (var i = 0; i < files.length; i++)
		{
			if ( typeof filestats[files[i]] == "undefined" )
			{
				return;
			}
		}

		callback(null, filestats);
	});
}

function statDir(dir, callback)
{
	fs.readdir(dir, function(err, files){
		if ( err )
		{
			callback(err);
		}
		else
		{
			var stats = {};
			for (var i = 0; i < files.length; i++)
			{
				statFile(dir, files[i], files, stats, callback);
			}
		}
	});
}

// Setup default arguments
var args = {
	help: false,
	path: ".",
	p: 8080
};

// Parse arguments
for (var i = 2; i < process.argv.length; i++)
{
	var arg = process.argv[i];
	if ( arg == "-h" || arg == "--help" )
	{
		args.help = true;
	}
	else if ( arg.indexOf("-") == 0 )
	{
		arg = arg.indexOf("--") == 0 ? arg.substring(2,arg.length) : arg.substring(1,arg.length);
		args[arg] = process.argv.length > i+1 && process.argv[i+1].indexOf("-") != 0 ? process.argv[++i] : true;
	}
	else if ( i == 2 )
	{
		// If first isn't an option we assume it's the path
		args.path = arg;
	}
}

// Show help if necessary
if ( args.help )
{
	console.log([
		"usage: serve [path] [options]","options:",
		"  -p                 Port to use [8080]"
	]);
	process.exit();
}

// Start the server
http.createServer(function(req, res){
	var uri = decodeURIComponent(url.parse(req.url).pathname);
	if ( uri.indexOf("..") != -1 )
	{
		error(res, 403);
	}
	else
	{
		var filename = path.join(args.path, uri);

		// Check if file exists and get stats
		fs.exists(filename, function(exists){
			if ( exists ){
				fs.stat(filename, function(err, stats){
					if ( stats && stats.isFile() )
					{
						serveFile(res, filename, stats);
					}
					else if ( stats && stats.isDirectory() )
					{
						serveDirectory(res, filename, uri);
					}
					else
					{
						error(res, 500);
					}
				});
			} else {
				error(res, 404);
			}
		});
	}
}).listen(args.p);

console.log("NodeServe running at " + path.resolve(args.path) + " on port " + args.p);